# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Encrata < Formula
  desc "Intelligence lookups from your terminal — email, phone, IP, domain, and OSINT"
  homepage "https://encrata.com"
  version "0.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Encratahq/encrata-cli/releases/download/v0.13.0/encrata_0.13.0_darwin_amd64.tar.gz"
      sha256 "0f2381e304d13efadf0a6fe568f9fc581459a6c5ea43a22d58466b2f796e6d34"

      define_method(:install) do
        bin.install "encrata"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Encratahq/encrata-cli/releases/download/v0.13.0/encrata_0.13.0_darwin_arm64.tar.gz"
      sha256 "6eaa765ab755c2ed48ad3410295624045161ff9aba16759afc15539204a7a78c"

      define_method(:install) do
        bin.install "encrata"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Encratahq/encrata-cli/releases/download/v0.13.0/encrata_0.13.0_linux_amd64.tar.gz"
      sha256 "262aee2a7fb77549fd8b5d5a693dc89008c50cfe2f9ebaa9c94bf8739f0aead7"
      define_method(:install) do
        bin.install "encrata"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Encratahq/encrata-cli/releases/download/v0.13.0/encrata_0.13.0_linux_arm64.tar.gz"
      sha256 "6657194d91cede70f83ed0e8138d445e3ea784d34dc67d6a1dbe41f675b9901f"
      define_method(:install) do
        bin.install "encrata"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/encrata version")
  end
end
