# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Encrata < Formula
  desc "Intelligence lookups from your terminal — email, phone, IP, domain, and OSINT"
  homepage "https://encrata.com"
  version "0.4.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Encratahq/encrata-cli/releases/download/v0.4.6/encrata_0.4.6_darwin_amd64.tar.gz"
      sha256 "a1b3e6ec415adfb4c46f20b630fe4e74a31e98bc71758f1b40b3b9eba5c84ad7"

      define_method(:install) do
        bin.install "encrata"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Encratahq/encrata-cli/releases/download/v0.4.6/encrata_0.4.6_darwin_arm64.tar.gz"
      sha256 "3b28facc257e9d938faef281b7a77a7f8a6a467b4cb4808cef84da79bf971767"

      define_method(:install) do
        bin.install "encrata"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Encratahq/encrata-cli/releases/download/v0.4.6/encrata_0.4.6_linux_amd64.tar.gz"
      sha256 "13647dd55f56904432cafafb6b7b964d73ceec9bcaf9c5000c980cdae56cd099"
      define_method(:install) do
        bin.install "encrata"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Encratahq/encrata-cli/releases/download/v0.4.6/encrata_0.4.6_linux_arm64.tar.gz"
      sha256 "79c9bc969d3b77f6edfd9338593e4af09b0ea1c1fd3429703b33e04a12eb61c7"
      define_method(:install) do
        bin.install "encrata"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/encrata version")
  end
end
